# Generated by Django 5.0.2 on 2024-04-29 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_rename_produits_commande_produits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='dateCde',
            field=models.DateField(default=datetime.date(2024, 4, 29), null=True),
        ),
    ]
